#!/usr/bin/with-contenv /bin/sh

# set PUID and PGID for www-data user/group
#
PUID=${PUID:-1000}
PGID=${PGID:-1000}

echo "[${0##*/}] uid: ${PUID}, gid: ${PGID}"

groupmod -o -g "$PGID" medusa
usermod -o -u "$PUID" -g "$PGID" medusa

