#!/usr/bin/env sh

# determine the version to install
case "${DOCKER_TAG}" in
	*0.3.9*)
		MEDUSA_COMMIT_HASH=d0c136d7a528a471b51676140bd35d24d97f65c6
		;;
	*0.3.12*)
		MEDUSA_COMMIT_HASH=ee1b898d0f74750c4c265d077fcc0da73d17b41e
		;;
	*0.3.15*|*)
		MEDUSA_COMMIT_HASH=8f6b6665c778cb456899809877c3bc15a547abf6
		;;
esac

# determine the Dockerfile to use
case "${DOCKER_TAG}" in
    *python*)
        DOCKERFILE="Dockerfile"
        ;;
	*pypy*)
		DOCKERFILE="Dockerfile.pypy"
		;;
	*minideb-pypy*)
		DOCKERFILE="Dockerfile.minideb-pypy"
		;;
	*minideb*)
		DOCKERFILE="Dockerfile.minideb"
		;;
    *)
        DOCKERFILE="Dockerfile"
        ;;
esac

echo "docker build --build-arg MEDUSA_COMMIT_HASH=${MEDUSA_COMMIT_HASH} -t ${IMAGE_NAME} -f ${DOCKERFILE} ."

docker build --build-arg MEDUSA_COMMIT_HASH=${MEDUSA_COMMIT_HASH} -t ${IMAGE_NAME} -f ${DOCKERFILE} .
