#!/usr/bin/env bash

. hooks/env

arg_string=''

[ ! -z "${TARGET_BUILD}" ] && arg_string="${arg_string} -f Dockerfile.${TARGET_BUILD}"
[ ! -z "${COMMIT_HASH}" ] && arg_string="${arg_string} --build-arg MEDUSA_COMMIT_HASH=${COMMIT_HASH}"

build_cmd=(docker build ${arg_string} -t ${IMAGE_NAME} .)

printf '\n---\n%s\n---\n\n' "${build_cmd[*]}"
"${build_cmd[@]}"
